### PR TITLE
removed /data since this is in HF, removed /examples and moved notebo…

### PR DESCRIPTION
**Pull request by jennamk14**
Removed /data directory, these files are in HF
Removed /examples directory and moved files to /notebooks 
Renamed notebook names for clarity

@dirtmaxim Can you update the names and add descriptions for dataset.ipynb and process.ipynb? not sure what these are for. thanks!

### CODE REVIEW

**Comment by zhong-al** [comment]
Isn't mini-scenes/model/* in [HF](https://huggingface.co/imageomics/x3d-kabr-kinetics)?

**Comment by jennamk14** [comment]
> Isn't mini-scenes/model/* in [HF](https://huggingface.co/imageomics/x3d-kabr-kinetics)?

yes, the models are in HF here: [imageomics/x3d-kabr-kinetics](https://huggingface.co/imageomics/x3d-kabr-kinetics/tree/main)

**Comment by hlapp** [comment]
> yes, the models are in HF here: [imageomics/x3d-kabr-kinetics](https://huggingface.co/imageomics/x3d-kabr-kinetics/tree/main)

Just FYI, that repo is still private; it seems like there's not much left though to make it public?

**Comment by jennamk14** [comment]
> > yes, the models are in HF here: [imageomics/x3d-kabr-kinetics](https://huggingface.co/imageomics/x3d-kabr-kinetics/tree/main)
> 
> Just FYI, that repo is still private; it seems like there's not much left though to make it public?

hi @hlapp we were waiting until we submit the manuscript to make the HF and github repos public

**Comment by egrace479** [comment]
The `data` folder is still in this branch, as is the example folder with the notebooks in it. It doesn't seem they were moved, but instead renamed and moved on your local machine then pushed up?

**Comment by egrace479** [comment]
Closing in favor of #51.

**Pull request closed without merging**
